-- 점검 이력 테이블 생성
create table inspection_reports (
  id bigint generated by default as identity primary key,
  equipment_id text not null default '-',
  equipment_name text not null,
  type text not null default '정기점검',
  inspector text not null,
  date date not null,
  result text not null default '이상없음',
  note text default '',
  created_at timestamp with time zone default now()
);

-- RLS 활성화
alter table inspection_reports enable row level security;

-- anon 키로 전체 접근 허용
create policy "allow_all" on inspection_reports
  for all using (true) with check (true);

-- 초기 데이터 삽입
insert into inspection_reports (equipment_id, equipment_name, type, inspector, date, result, note) values
('TR-001', '주변압기 1호', '정기점검', '김철수', '2026-05-20', '이상없음', '오일 샘플 채취, 권선저항 측정 완료'),
('GEN-002', '발전기 2호', '예방점검', '이영희', '2026-05-25', '점검중', '베어링 교체 작업 진행 중 (완료 예정: 05/28)'),
('CB-001', '차단기 1번', '동작시험', '박민준', '2026-05-21', '이상없음', '개폐 동작 확인, 접점 마모 미미'),
('MOT-001', '펌프 모터 1', '절연저항측정', '최수진', '2026-05-22', '이상없음', '절연저항 450MΩ 측정, 양호'),
('CAB-001', '154kV 케이블 1', '부분방전측정', '정대현', '2026-05-15', '요주의', '부분방전 2.5pC 감지, 정밀진단 예약 필요'),
('DP-001', '배전반 A-1', '청소 및 점검', '한지수', '2026-05-23', '이상없음', '내부 청소, 단자 체결 확인');
